apiVersion: v1
kind: Secret
metadata:
  name: redispw
type: Opaque
data:
  password: TWFuZ2VUZXNNb3J0cw==
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default
data:
  users: Z3JhYmk6JGFwcjEkdHdwMnIwOW0kbi9YMWM3T0psTmduLnBQWnBmcXBaMQ==